#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap ch &
nitrogen --restore
picom

#bspc monitor -d I II III IV V VI VII VIII IX X

# --- incluído após a instalação --- #

# início da modificação


bspc monitor DisplayPort-0 -d I II III IV V
bspc monitro HDMI-A-0 -d VI VII VIII IX X

$HOME/.config/polybar/launch.sh

# fim da modificação

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
