#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap ch &
nitrogen --restore
picom &
$HOME/.config/polybar/launch.sh &

#bspc monitor -d I II III IV V VI VII VIII IX X

# --- incluído após a instalação --- #

# início da modificação
bspc monitor DisplayPort-0 -d I
bspc monitor HDMI-A-0 -d II III IV V VI VII
# fim da modificação

# adicionado linhas (início)

#bspc config click_to_focus true
bspc config pointer_modifier mod4 # Super key to mouse actions
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config border_width         3    
bspc config window_gap          10
bspc config top_padding         10
bspc config left_padding         0
bspc config right_padding        0
bspc config bottom_padding       0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true
bspc config automatic_scheme longest_side
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# moficiando a cor para "#4bffdc"
# modificação atual de cor "#2222ff"

bspc config normal_border_color "#BDCCB2"
#bspc config normal_border_color "#2222ff"

bspc config active_border_color "#2222ff"
#bspc config active_border_color "#5AAE5F"

bspc config focused_border_color "#2222ff"
#bspc config focused_border_color "#5AAE5F"

bspc config urgent_border_color "#FF4500"
#bspc config urgent_border_color "#2222ff"

bspc config presel_border_color "#2222ff"
#bspc config presel_border_color "#5AAE5F"

bspc config presel_feedback_color "#2222ff"
#bspc config presel_feedback_color "#5AAE5F"

bspc rule -a '*:libreoffice' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Firefox state=floating
bspc rule -a Firefox:Navigator state=tiled

# srandr for handle displays output
sleep 2
srandrd -e "$dot_s"/display_handler.sh &

# fim das linhas
